name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit Test

      - name: App
        run: ./gradlew testDebugUnitTest
      - name: Domain
        run: ./gradlew domain:testDebugUnitTest
      - name: Data
        run: ./gradlew data:testDebugUnitTest
      - name: Data.Room
        run: ./gradlew data:room:testDebugUnitTest
      - name: Data.Retrofit
        run: ./gradlew data:retrofit:testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
